### ISSUE TITLE
Files EMAIL_ME and PUT_ME_ON_DESKTOP are not being created

### ISSUE THREAD

**Issue by DominikR1** [ncorbuk/Python-Ransomware#10]
Hi,
Whenever I open up the RansomWare.py file on the victim machine, the files EMAIL_ME and PUT_ME_ON_DESKTOP are not being created. The files in the localroot folder are getting encrypted, but the files are not there, the background stays the same and the webpage bitcoin.org doesn't show up. I have of course changed the path to what is required, but the other features don't work. Could you help? Thanks in advance!
![dfjbdfifssbivvs](https://user-images.githubusercontent.com/66365320/121533048-30a71880-ca00-11eb-8ad3-313c4e1f029d.PNG)

**Comment by yashmodi17** [comment]
> Hi,
> Whenever I open up the RansomWare.py file on the victim machine, the files EMAIL_ME and PUT_ME_ON_DESKTOP are not being created. The files in the localroot folder are getting encrypted, but the files are not there, the background stays the same and the webpage bitcoin.org doesn't show up. I have of course changed the path to what is required, but the other features don't work. Could you help? Thanks in advance!
> ![dfjbdfifssbivvs](https://user-images.githubusercontent.com/66365320/121533048-30a71880-ca00-11eb-8ad3-313c4e1f029d.PNG)

Bro did you find the solution to this issue?

**Comment by yashmodi17** [comment]
Help me I have the same issue

**Comment by yashmodi17** [comment]
@DominikR1  please help brother same issue
