### ISSUE TITLE
File or directory not found  can you please help me The one who would solve my query i will give 50$ via paypal so  with your solution leave ur paypal details

### ISSUE THREAD

**Issue by yashmodi17** [ncorbuk/Python-Ransomware#11]
![Screenshot (24)](https://user-images.githubusercontent.com/63386752/125156726-96fc9380-e184-11eb-9b87-97dec4636546.png)
Traceback (most recent call last):
  File "Ransomware.py", line 250, in <module>
    main()
  File "Ransomware.py", line 232, in main
    rw.encrypt_fernet_key()
  File "Ransomware.py", line 84, in encrypt_fernet_key
    with open(f'{self.sysRoot}Desktop/EMAIL_ME.txt', 'wb') as fa:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\AdminDesktop/EMAIL_ME.txt'

**Comment by dv8081** [comment]
search for EMAIL_ME.txt on whole pc if you got that then copy and paste it on desktop and and try again for decrypt.

**Comment by yashmodi17** [comment]
> search for EMAIL_ME.txt on whole pc if you got that then copy and paste it on desktop and and try again for decrypt.

I am not getting it

**Comment by dv8081** [comment]
check this https://github.com/Ciphey/Ciphey

**Comment by RubelPerez** [comment]
> ![Screenshot (24)](https://user-images.githubusercontent.com/63386752/125156726-96fc9380-e184-11eb-9b87-97dec4636546.png) Traceback (most recent call last): File "Ransomware.py", line 250, in main() File "Ransomware.py", line 232, in main rw.encrypt_fernet_key() File "Ransomware.py", line 84, in encrypt_fernet_key with open(f'{self.sysRoot}Desktop/EMAIL_ME.txt', 'wb') as fa: FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\AdminDesktop/EMAIL_ME.txt'

is because you are looking EMAIL_ME.txt in C:\Users\AdminDesktop\EMAIL_ME.txt when **must be** C:\Users\Admin\Desktop\EMAIL_ME.txt
