### ISSUE TITLE
Make it Persistence

### ISSUE THREAD

**Issue by pickledrick** [ncorbuk/Python-Ransomware#6]
If the victim reboots the PC after the encryption, the program doesn't run on start-up hence it doesn't look for the put_me_on_desktop.txt anymore so files can not be decrypted.

**Comment by dv8081** [comment]
> If the victim reboots the PC after the encryption, the program doesn't run on start-up hence it doesn't look for the put_me_on_desktop.txt anymore so files can not be decrypted. 
Turn ransom.py in exe. And try again

**Comment by pickledrick** [comment]
Tried that already, it just encrypts the encrypted files again and creates another fernet key. But I have figured out a way to tackle that, I'll just separate the decryption script from ransomware, then ask her to place the put the key on desktop then run it again.
I have ano

> > If the victim reboots the PC after the encryption, the program doesn't run on start-up hence it doesn't look for the put_me_on_desktop.txt anymore so files can not be decrypted.
> > Turn ransom.py in exe. And try again

Tried that already, it just encrypts the encrypted files again and creates another fernet key. But I have figured out a way to tackle that, I'll just separate the decryption script from ransomware, then ask the victim to place the put the key on desktop then to run the script.
I have another question though, if start encryption from sysroot, will encrypt all the drives too?

**Comment by ncorbuk** [comment]
Yea this is just a basic outline of how you can go about making a simple ransomware in Python. It is for you to change about, edit, and make better and so on. If you want to add persistence it will depend on with OS you want it to be for. If Linux look into crontab, and if windows look into registry and add appropriate code etc. :)
